apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosi-driver-garage
  namespace: system
  labels:
    app.kubernetes.io/name: cosi-driver-garage
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cosi-driver-garage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cosi-driver-garage
    spec:
      serviceAccountName: cosi-driver-garage
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      containers:
        - name: driver
          securityContext:
            readOnlyRootFilesystem: true
          image: driver
          volumeMounts:
            - name: cosi-socket-dir
              mountPath: /var/lib/cosi
          envFrom:
            - secretRef:
                name: cosi-driver-garage
          resources:
            requests:
              cpu: 25m
              memory: 64M
            limits:
              memory: 256M

        - name: objectstorage-provisioner-sidecar
          image: sidecar
          args:
            - "-v=4"
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: cosi-socket-dir
              mountPath: /var/lib/cosi
          resources:
            requests:
              cpu: 25m
              memory: 64M
            limits:
              memory: 256M

      volumes:
        - name: cosi-socket-dir
          emptyDir: {}
