apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - role.yaml
  - rolebinding.yaml
  - sa.yaml

images:
  - name: driver
    newName: ghcr.io/mpreu/cosi-driver-garage/cosi-driver-garage
    newTag: 0.1.0

  - name: sidecar
    newName: gcr.io/k8s-staging-sig-storage/objectstorage-sidecar/objectstorage-sidecar
    newTag: v20230130-v0.1.0-24-gc0cf995
