linters:
  # Additionally enabled linters.
  enable:
    - copyloopvar
    - dogsled
    - dupl
    - exhaustive
    - goconst
    - godot
    - gofumpt
    - goimports
    - importas
    - mnd
    - revive
    - unconvert
    - unparam
    - whitespace
  fast: false
linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  goimports:
    local-prefixes: github.com/mpreu/cosi-driver-garage
