kind: BucketClaim
apiVersion: objectstorage.k8s.io/v1alpha1
metadata:
  name: garage-test
spec:
  bucketClassName: garage
  protocols:
    - s3
---
kind: BucketAccess
apiVersion: objectstorage.k8s.io/v1alpha1
metadata:
  name: garage-test
spec:
  bucketClaimName: garage-test
  bucketAccessClassName: garage
  credentialsSecretName: bucket-creds-garage-test
  protocol: s3
