kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cosi-driver-garage-anyuid
  labels:
    app.kubernetes.io/name: cosi-driver-garage
subjects:
  - kind: ServiceAccount
    name: cosi-driver-garage
    namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
